// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Health, HealthData, HealthTableId } from "./tables/Health.sol";
import { ChestId, ChestIdTableId } from "./tables/ChestId.sol";
import { Nullifier, NullifierTableId } from "./tables/Nullifier.sol";
import { Points, PointsTableId } from "./tables/Points.sol";
import { Coins, CoinsTableId } from "./tables/Coins.sol";
import { Guild, GuildTableId } from "./tables/Guild.sol";
