// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGuildSystem {
  function createGuild(bytes32 guildId, bytes32[] memory members) external returns (bytes32);
}
